# Generated by Django 4.1.7 on 2023-07-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.TextField(max_length=10),
        ),
    ]
