# Generated by Django 4.1.7 on 2023-07-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_connectednotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectednotification',
            old_name='sou',
            new_name='source',
        ),
    ]
