# Generated by Django 4.0 on 2023-08-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_chatmessage_file_data_chatmessage_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='file_data',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='filename',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments'),
        ),
    ]
