# Generated by Django 4.0 on 2023-08-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_remove_message_file_alter_chatmessage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='file',
        ),
    ]
