# Generated by Django 4.0 on 2023-08-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_alter_chatmessage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
