# Generated by Django 4.0 on 2023-08-03 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_defaultgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultGroup',
        ),
    ]
